name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cargo test
        uses: actions/checkout@v3
        run: cargo test --verbose --locked --all-features --all-targets
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: cargo fmt
        uses: actions/checkout@v3
        run: cargo fmt --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: cargo clippy
        uses: actions/checkout@v3
        run: |
          cargo clippy -- -W clippy::all -W clippy::pedantic \
          -A clippy::used-underscore-binding \
          -A clippy::doc_markdown \
          -A clippy::needless_pass_by_value \
          -A clippy::must_use_candidate \
          -A clippy::return_self_not_must_use \
          -A clippy::missing_errors_doc \
          -A clippy::single_match \
          -A clippy::uninlined_format_args \
          -A clippy::no_effect_underscore_binding \
          -A clippy::large_futures
